### ISSUE TITLE
How to generate a trace with STD format

### ISSUE THREAD

**Issue by DemoAuguste** [umangm/rapid#1]
I'm confused with how to generate a trace with STD/CSV format.
Could you please tell me what command I should use?
Thanks.

**Comment by umangm** [comment]
Hi @DemoAuguste,
RAPID does not come with its own logger, and relies on other tools like RVPredict or RoadRunner to generate traces.
Once you have traces generated from these tools, you can use them in RAPID, either directly or after converting them to a more readable format like CSV or STD.

Instructions for generating traces using [RVPredict](https://runtimeverification.com/predict/) are given in the readme: https://github.com/umangm/rapid/blob/master/README.md
Instructions for generating traces using [RoadRunner](https://github.com/stephenfreund/RoadRunner) are here: https://github.com/umangm/rapid/blob/master/notes/Generate_RoadRunner_traces.md

Instructions for converting traces in any format to CSV or STD:
```
cd rapid/
ant jar
java -cp ./lib/*:rapid.jar <PrintClass> -f <format> -p <path>
```
Here,
-  `<PrintClass>` is either `PrintSTD` or `PrintCSV` depending upon the output format you want.
- `<format>` is `rr` if the traces have been generated using RoadRunner. In this case `<path>` is the path to the log file.
- `<format>` is `rv` if the traces have been generated using RVPredict. In this case, `<path>` is the path to the folder that contains the binary files.

**Tip**: I would recommend using the STD format over the CSV format. The CSV format does not handle fork joins elegantly.

**Comment by DemoAuguste** [comment]
Hi @umangm 
Thanks for your reply. But I tried instructions you told me and I encountered with the following exception:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/cli/ParseException
	at PrintSTD.main(PrintSTD.java:13)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.cli.ParseException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more
```

My instructions are as follows:
```
git clone git@github.com:umangm/rapid.git
cd rapid
ant build
ant jar
java -cp ./lib/*:rapid.jar PrintSTD -f rv -p ../base_log_dir/test/
```
I wonder if I have missed some critical steps so I can not generate the right outputs.

**Comment by umangm** [comment]
The last commit was about 6 hours ago, so please make sure you pull before you start.
Also can you paste the outputs of the following command for me:

`ant clean; ls lib/; ant build; ant jar #assuming you are in the folder rapid/`

**Comment by DemoAuguste** [comment]
I have got the right output successfully. Thank you very much!
I am also doing some research on data race detection. Your paper and work are excellent and interesting. Hope to have a further communication with you.

**Comment by umangm** [comment]
Thank you! We can take this conversation offline. My email is umathur3@illinois.edu
I would like to know more about your research !
