### ISSUE TITLE
How to detect data races using Rapid?

### ISSUE THREAD

**Issue by bupt01** [umangm/rapid#2]
Hello, after receiving your source code, I feel a bit lost and don't know how to run it. Do you have any basic usage tutorials?

**Comment by zhengshi1998** [comment]
Hi, rapid is a offline analysis tool. To use rapid, you need to generate some program traces using other tools, such as RV-Predict. Then rapid offers some algorithm options to analysis the data races within the log. Here we provided a few sample traces from other programs. 

https://drive.google.com/file/d/1e76onK_a0SOHrEJfiNWpwYR0Wbv_Opu0/view?usp=drive_link 

For example I want to apply SHB algo to analyze the trace. Then I goto main function of `SHB.java` file. You can see it receives some command line options and call the `SHBEngine` to analyze the trace. To make it simple, you can comment out the `CmdOptions` line and change the `SHBEngine / analyzeTrace` line into the following.

```
SHBEngine engine = new SHBEngine(ParserType.STD, [dir to the std trace]);
engine.analyzeTrace(true, 0);
```
Here [dir to the std trace] means the location of the std trace file you downloaded from the link above. Then if you run the main function, it will do SHB on the trace, and prints out some analysis result.

**Comment by bupt01** [comment]
Thank you for your prompt response despite your busy schedule. I will carefully study the information you provided. Your work will undoubtedly inspire and assist us greatly.
