### ISSUE TITLE
Issue with RoadRunner not stopping when generating traces for Rapid

### ISSUE THREAD

**Issue by bupt01** [umangm/rapid#3]
Recently, I've been using Rapid to detect data races and employing RoadRunner to record and generate traces(rrrun -noFP -tool=P -values -noxml -noEnter -quiet ). However, I quickly noticed that RoadRunner's recording of traces doesn't seem to stop at all.In many benchmarks, this seems to be a common issue, such as in benchmarks like Moldyn and Raytracer.In contrast, running the tested program directly concludes within a few seconds. While recording traces may naturally slow down the execution speed, the pace of RoadRunner seems excessively abnormal. Additionally, the generated number of traces is exceptionally high, reaching hundreds of millions of events. This is significantly different from the event counts reported in the literature for other data race detection tools.

Initially, I thought about filtering out some Java packages, such as org.apache.*, but I learned from the literature that RoadRunner only instruments application code, not Java library code. Therefore, that reasoning doesn't hold. I would like to know if there is something I overlooked that might be causing this issue.

**Comment by bupt01** [comment]
I have resolved the issue, and it was due to incorrect Java Virtual Machine parameters settings

**Comment by bupt01** [comment]
I have now ruled out the issue of java Virtual machine parameters, and this is still the case when running some programs

**Comment by umangm** [comment]
I concur with your observation. At the time I did my experiments, I did not explicitly try to debug this. In short, I did run the trace generation phase for several hours for each benchmark.
