### ISSUE TITLE
Why doesn't Rapid handle wait/notify events?

### ISSUE THREAD

**Issue by bupt01** [umangm/rapid#4]
Hello, while studying Rapid, I noticed that it doesn't handle wait/notify events. It only deals with "Acquire", "Release", "[A]?Rd", "[A]?Wr", "Start", "Join", "Enter", "Exit", "Dummy", and "Br" events. However, in reality, there is a sequential relationship between the two. If not handled, could this lead to false positives?
Looking forward to your response, I'm fortunate to be able to communicate with you!

**Comment by umangm** [comment]
At the moment, we expect the users to replace wait and notify by some other events to capture the dependencies from wait and notify. 

Adding support for wait/notify event types was work in progress at some point, but then I got busy and did not follow up. Do you think you want to take it up and submit pull requests?
